### ISSUE TITLE
micro_aust

### ISSUE THREAD

**Issue by green-striped-gecko** [mrke/NicheMapR#16]
Hi,
when running the mico_aust function to get the microclimate for an Australian location I get the following error. 
Error in RNetCDF::open.nc(paste0(baseurl, var, "/day/", year, "/bom-",  : 
  NetCDF: Malformed or inaccessible DAP DDS

When tracing back I think the problem lies in the provided baseurl to get the climate data as this is no longer available. I tried to find the correct link but could not find it. Currenlty it points to:

"http://rs-data1-mel.csiro.au/thredds/dodsC/bawap/"

which does not work anymore.

Any help here?

Thanks and cheers, Bernd

**Comment by mrke** [comment]
Hi Bernd,

Sorry that data is indeed no longer available. If you look here https://data.gov.au/dataset/ds-bom-ANZCW0503900567/details?q= you’ll see there’s a plan to make it available for the full time period via opendap. I’ll put that functionality in there as soon as it is. Otherwise, you can use micro_ncep or micro_era5.

All the best,
Mike

From: Bernd Gruber ***@***.***>
Sent: Tuesday, 27 July 2021 9:45 AM
To: mrke/NicheMapR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [mrke/NicheMapR] micro_aust (#16)

External email: Please exercise caution

________________________________
Hi,
when running the mico_aust function to get the microclimate for an Australian location I get the following error.
Error in RNetCDF::open.nc(paste0(baseurl, var, "/day/", year, "/bom-", :
NetCDF: Malformed or inaccessible DAP DDS

When tracing back I think the problem lies in the provided baseurl to get the climate data as this is no longer available. I tried to find the correct link but could not find it. Currenlty it points to:

"http://rs-data1-mel.csiro.au/thredds/dodsC/bawap/<http://rs-data1-mel.csiro.au/thredds/dodsC/bawap>"

which does not work anymore.

Any help here?

Thanks and cheers, Bernd
