### ISSUE TITLE
micro_aust doesn't work for dates before 1990

### ISSUE THREAD

**Issue by crg311** [mrke/NicheMapR#8]
Hi mrke,
I've been trying to use micro_aust and ectotherm to calculate microclimate variables and lizard activity times for dates between 1920 and 2006. I've had success running micro_aust for dates after 1990 but dates earlier than 1990 end up with this error when extracting the climate data: 

Error in RNetCDF::open.nc(paste0(baseurl, var, "/day/", year, "/bom-",  : 
  NetCDF: file not found

I saw on your website that micro_aust can calculate microclimates from 1911 onwards, so I'm not sure why this error is occurring! Any help would be appreciated!
Thanks,
Chris

**Comment by mrke** [comment]
Hi Chris,

That’s because the opendap connection is only from 1990 to about 2017, unfortunately. I’ve set up a local database of the data from 1911 that updates each day, and you can access that if you use the web app of the micro_aust function, but I’ve only allowed that to run for 1.5 years (half a year of spin up) so as not to drain the resources of that server.

All the best,
Mike
